ERP-3773 Show overdue amount in ledger
Dehaat/ledger-sdk pull request #18
Opened 2022-11-03 05:15 UTC by ankur-singh-dehaat

2022-11-03 05:19 UTC, shivam21 commented
@ankur-singh-dehaat please correct commit id in commit

2022-11-07 06:58 UTC, anil-agridroid requested changes

2022-11-07 06:58 UTC, anil-agridroid commented on lib-ledger/src/main/java/lib/dehaat/ledger/presentation/mapper/LedgerViewDataMapper.kt
> +    private fun Double.isPositive() = this > 0.0
Change fun name to isGreaterThanZero

2022-11-07 06:58 UTC, anil-agridroid commented on lib-ledger/src/main/java/lib/dehaat/ledger/presentation/mapper/LedgerViewDataMapper.kt
> +    private fun Double.isNegative() = this < 0.0
Use fun name isSmallerThanZero

2022-11-07 07:12 UTC, ankur-singh-dehaat commented on lib-ledger/src/main/java/lib/dehaat/ledger/presentation/mapper/LedgerViewDataMapper.kt
> +    private fun Double.isNegative() = this < 0.0
addressed, can you please review this again?

2022-11-07 07:28 UTC, merged