weekly interest label
Dehaat/ledger-sdk pull request #32
Opened 2023-02-10 12:55 UTC by ankur-singh-dehaat

2023-02-20 10:17 UTC, shivam21 requested changes

2023-02-20 10:17 UTC, shivam21 commented on lib-ledger/src/main/java/lib/dehaat/ledger/entities/revamp/transaction/TransactionEntityV2.kt
> +    val fromDate: Long?,
format

2023-02-20 10:17 UTC, shivam21 commented on lib-ledger/src/main/java/lib/dehaat/ledger/presentation/ledger/revamp/state/transactions/ui/TransactionsScreen.kt
> +                                    Color(0xff3985BF),
move colors to Colors.kt

2023-02-20 10:17 UTC, shivam21 commented on lib-ledger/src/main/java/lib/dehaat/ledger/presentation/mapper/LedgerViewDataMapper.kt
> +            fromDate = it.fromDate?.toDateMonthYear(),
format

2023-02-21 05:50 UTC, lovemhjn approved these changes
lgtm

2023-02-21 10:31 UTC, merged