[FTS-1558] Ledger outstanding ui enhancement
Dehaat/ledger-sdk pull request #61
Opened 2023-06-13 09:13 UTC by ankur-singh-dehaat

2023-06-22 12:52 UTC, lovemhjn requested changes

2023-06-22 12:52 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/bottomsheets/OutstandingCalculationScreen.kt
> +	Row(
Breakdown this composable into smaller composables

2023-06-22 12:52 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/transactions/ui/component/AbsBanner.kt
> +				remember(abs?.amount) { abs?.amount?.orZero().toString().getAmountInRupees() }
This should be moved to mapper

2023-06-22 12:52 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/util/UIExtensions.kt
> +					if (LedgerSDK.isDebug) {
Why we are doing this? if (LedgerSDK.isDebug)

2023-06-23 05:24 UTC, ankur-singh-dehaat commented on src/main/java/lib/dehaat/ledger/presentation/ledger/transactions/ui/component/AbsBanner.kt
> +				remember(abs?.amount) { abs?.amount?.orZero().toString().getAmountInRupees() }
If we move this to viewMapper this field will be duplicated, we are using amount for comparison and population.
cc @shivam21

2023-06-23 05:26 UTC, ankur-singh-dehaat commented on src/main/java/lib/dehaat/ledger/util/UIExtensions.kt
> +					if (LedgerSDK.isDebug) {
This will show exact error message on debug builds, like if any field is non-null and it is coming as null error message will show that and QA will easily identify issue, and on non-debug builds we will show something went wrong error message.

2023-06-23 05:48 UTC, shivam21 approved these changes
lgtm

2023-06-23 08:31 UTC, lovemhjn approved these changes

2023-06-23 12:16 UTC, merged