[ERP-6532] Main Ledger changes for wallet
Dehaat/ledger-sdk pull request #68
Opened 2023-08-02 08:43 UTC by amantheshooter

2023-08-03 05:20 UTC, lovemhjn requested changes

2023-08-03 05:20 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/RevampLedgerViewModel.kt
> +        callingAPI()
rename this

2023-08-03 05:20 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/revamp/state/transactions/ui/TransactionsScreen.kt
> +			valueText = walletBalance.getAmountInRupees(),
move walletBalance.getAmountInRupees() to view mapper class

2023-08-03 05:20 UTC, lovemhjn commented on src/main/res/drawable/ic_lock_orange_bg.xml
> +      android:fillColor="#FFFFFF"/>
Check if this doesn't override any existing usage

2023-08-03 07:14 UTC, sachin-varshney approved these changes

2023-08-09 06:58 UTC, shivam21 commented on src/main/java/lib/dehaat/ledger/navigation/LedgerNavigation.kt
> +	            openOrderDetailFragment(it, it)
send only orderId LedgerExecutor already have partnerId

2023-08-14 12:41 UTC, amantheshooter commented on src/main/java/lib/dehaat/ledger/presentation/RevampLedgerViewModel.kt
> +        callingAPI()
this is old function of ledger view model, I have just used it, Currently not doing it.

2023-08-14 17:57 UTC, merged