[ERP-6109] Remove AWS dependency for input backend APIs
Dehaat/ledger-sdk pull request #72
Opened 2023-08-07 07:49 UTC by tanya-06

2023-08-07 10:35 UTC, shivam21 requested changes

2023-08-07 10:35 UTC, shivam21 commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +        val test = Intent(Intent.ACTION_VIEW)
please rename test more intuitive name

2023-08-07 10:35 UTC, shivam21 commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +    private fun handleDownloadProgress(
check if we don't require to show progress percentage, we can use broadcast receiver as in download ledger statement else add some delay(300-500ms) in while loop. we don't need every millisecond progress

2023-08-08 04:30 UTC, lovemhjn requested changes

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/details/invoice/InvoiceDetailViewModel.kt
> +        fileName = fileName.substring(0, 1).uppercase() + fileName.substring(1)
Use string.replaceFirstChar() method it handles empty string cases internally

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/details/invoice/RevampInvoiceDetailViewModel.kt
> +        fileName = fileName.substring(0, 1).uppercase() + fileName.substring(1)
same as above

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/details/invoice/ui/RevampInvoiceDetailScreen.kt
> +	viewModel: RevampInvoiceDetailViewModel,
No need to pass the viewmodel instance to function. Just pass the required function call as parameter

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/presentation/ledger/details/invoice/ui/InvoiceDetailScreen.kt
> +    viewModel: InvoiceDetailViewModel,
No need to pass the viewmodel instance to function. Just pass the required function call as parameter

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +                    cursor.getColumnIndex(DownloadManager.COLUMN_LOCAL_URI)
Use getColumnIndexOrThrow instead and wrap this entire code block inside try catch and log non fatal exceptions to firebase

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +        while (!finishDownload) {
Not a safe operation. Might get stackoverflow exception

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +                                val totalBytes = cursor.getLong(totalSizeIndex)
Use getLongOrNull and handle accordingly

2023-08-08 04:30 UTC, lovemhjn commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +                val localUriString = cursor.getString(columnIndex)
Use getStringOrNull and handle accordingly

2023-08-09 10:15 UTC, shivam21 commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +            Thread.sleep(500)
Double check, this will block main thread.

2023-08-09 10:46 UTC, shivam21 commented on src/main/java/lib/dehaat/ledger/util/DownloadFileUtil.kt
> +                delay(500)
this will also block main thread

2023-08-22 11:44 UTC, shivam21 approved these changes
lgtm

2023-08-29 07:46 UTC, lovemhjn approved these changes

2023-08-29 07:47 UTC, merged